server:
  port: 9292
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edufinity_course?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      
  servlet:
    multipart:
      max-file-size: 10mb
      max-request-size: 12mb
    